# Generated by Django 3.0.3 on 2020-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='facts',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='facts',
            name='fact',
            field=models.TextField(default=''),
        ),
    ]
